/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedACobrarRouteImport } from './routes/_authenticated/a-cobrar'
import { Route as AuthenticatedAgendamentosRouteImport } from './routes/_authenticated/agendamentos'
import { Route as AuthenticatedBoletosRouteImport } from './routes/_authenticated/boletos'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedNotasFiscaisRouteImport } from './routes/_authenticated/notas-fiscais'
import { Route as AuthenticatedProntosRouteImport } from './routes/_authenticated/prontos'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedACobrarRoute = AuthenticatedACobrarRouteImport.update({
  id: '/a-cobrar',
  path: '/a-cobrar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendamentosRoute =
  AuthenticatedAgendamentosRouteImport.update({
    id: '/agendamentos',
    path: '/agendamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoletosRoute = AuthenticatedBoletosRouteImport.update({
  id: '/boletos',
  path: '/boletos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotasFiscaisRoute =
  AuthenticatedNotasFiscaisRouteImport.update({
    id: '/notas-fiscais',
    path: '/notas-fiscais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProntosRoute = AuthenticatedProntosRouteImport.update({
  id: '/prontos',
  path: '/prontos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/a-cobrar': typeof AuthenticatedACobrarRoute
  '/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/boletos': typeof AuthenticatedBoletosRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/notas-fiscais': typeof AuthenticatedNotasFiscaisRoute
  '/prontos': typeof AuthenticatedProntosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/a-cobrar': typeof AuthenticatedACobrarRoute
  '/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/boletos': typeof AuthenticatedBoletosRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/notas-fiscais': typeof AuthenticatedNotasFiscaisRoute
  '/prontos': typeof AuthenticatedProntosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/a-cobrar': typeof AuthenticatedACobrarRoute
  '/_authenticated/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/_authenticated/boletos': typeof AuthenticatedBoletosRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/notas-fiscais': typeof AuthenticatedNotasFiscaisRoute
  '/_authenticated/prontos': typeof AuthenticatedProntosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/a-cobrar'
    | '/agendamentos'
    | '/boletos'
    | '/caixa'
    | '/clientes'
    | '/dashboard'
    | '/estoque'
    | '/financeiro'
    | '/notas-fiscais'
    | '/prontos'
    | '/usuarios'
    | '/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/a-cobrar'
    | '/agendamentos'
    | '/boletos'
    | '/caixa'
    | '/clientes'
    | '/dashboard'
    | '/estoque'
    | '/financeiro'
    | '/notas-fiscais'
    | '/prontos'
    | '/usuarios'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/a-cobrar'
    | '/_authenticated/agendamentos'
    | '/_authenticated/boletos'
    | '/_authenticated/caixa'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/estoque'
    | '/_authenticated/financeiro'
    | '/_authenticated/notas-fiscais'
    | '/_authenticated/prontos'
    | '/_authenticated/usuarios'
    | '/_authenticated/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/a-cobrar': {
      id: '/_authenticated/a-cobrar'
      path: '/a-cobrar'
      fullPath: '/a-cobrar'
      preLoaderRoute: typeof AuthenticatedACobrarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agendamentos': {
      id: '/_authenticated/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AuthenticatedAgendamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boletos': {
      id: '/_authenticated/boletos'
      path: '/boletos'
      fullPath: '/boletos'
      preLoaderRoute: typeof AuthenticatedBoletosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas-fiscais': {
      id: '/_authenticated/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/notas-fiscais'
      preLoaderRoute: typeof AuthenticatedNotasFiscaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prontos': {
      id: '/_authenticated/prontos'
      path: '/prontos'
      fullPath: '/prontos'
      preLoaderRoute: typeof AuthenticatedProntosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedACobrarRoute: typeof AuthenticatedACobrarRoute
  AuthenticatedAgendamentosRoute: typeof AuthenticatedAgendamentosRoute
  AuthenticatedBoletosRoute: typeof AuthenticatedBoletosRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedNotasFiscaisRoute: typeof AuthenticatedNotasFiscaisRoute
  AuthenticatedProntosRoute: typeof AuthenticatedProntosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedACobrarRoute: AuthenticatedACobrarRoute,
  AuthenticatedAgendamentosRoute: AuthenticatedAgendamentosRoute,
  AuthenticatedBoletosRoute: AuthenticatedBoletosRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedNotasFiscaisRoute: AuthenticatedNotasFiscaisRoute,
  AuthenticatedProntosRoute: AuthenticatedProntosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
